[package]
name = "day23"
version = "0.1.0"
authors = ["Hugo Buddelmeijer <hugo@buddelmeijer.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
debug = true
