name = {ASCII_DIGIT+}
andterms = {name ~ (" " ~ name)*}
orterms = {andterms ~ (" | " ~ andterms)*}
letter = {"\"" ~ ASCII_ALPHA ~ "\""}
rule = {name ~ ": " ~ (orterms | letter)}
rules = {(rule ~ "\n")+}
monster = {ASCII_ALPHA+}
monsters = {(monster ~ "\n")+}
file = { SOI ~ rules ~ "\n" ~ monsters ~ EOI}

p0 = { SOI ~ (p4 ~ p1 ~ p5) ~ EOI}
p1 = {(p2 ~ p3) | (p3 ~ p2)}
p2 = {(p4 ~ p4) | (p5 ~ p5)}
p3 = {(p4 ~ p5) | (p5 ~ p4)}
p4 = {"a"}
p5 = {"b"}
